### ISSUE TITLE
automatic prefix in select into struct

### ISSUE THREAD

**Issue by afriza** [ganigeorgiev/ozzo-dbx#1] opened 2022-07-21 17:33 UTC
There are these phrases in the [README](https://github.com/pocketbase/dbx#executing-queries):

> - For named fields that are of struct type, they will also be expanded. But their component fields will be prefixed with the struct names when being populated.

and also

> - `Address.City`: to be populated from the `addr.city` column, since `Address` is a named field of struct type and its fields will be prefixed with `addr.` according to the `db` tag.

But if I `SELECT addr.*, table2.* FROM addr JOIN table2 ...`, these prefix mechanism is not automatic.

I have to do `SELECT addr.city 'addr.city', table2.col1 'table2.col1', ... FROM addr JOIN table2 ...` for this prefix mechanism to work..

Do you plan to to make it work or have any idea where/how to make it work?

**Comment by ganigeorgiev** [comment] 2022-07-27 10:36
Hi, sorry for the late reply (for some reason I wasn't a watcher to the repo and didn't receive a notification).

Anyway, I think this is an intended behavior and I'm not sure that it would be safe to change it without breaking someone else's code.

I haven't tested it, but the part of the code that should be responsible for this should be the struct columns build mapper - https://github.com/pocketbase/dbx/blob/8402f60f16599c203a8c0baed20194f4322c1cb1/struct.go#L184-L186.

I'll close the issue since I don't want to introduce breaking changes, but if you think that this could be done in a backward compatible manner, then feel free to open a PR and I'll review it.

**Closed as completed by ganigeorgiev** 2022-07-27 10:36 UTC
