### ISSUE TITLE
dbx.Query Delete does not honor cascade delete

### ISSUE THREAD

**Issue by geerew** [ganigeorgiev/ozzo-dbx#3] opened 2023-05-26 12:50 UTC
I have 2 tables; 1 table has an an ID and the other has a foreign key reference to the ID and an `on cascade delete`

When I use Delete(), for example `dbx.Delete("TABLE1", dbx.HashExp{"id" : id}).Execute()`, the cascasde delete does NOT happen and the referenced rows in table 2 remain

However, If I do a raw sql, for example `dbx.NewQuery(fmt.Sprintf("DELETE FROM TABLE1 where id = '%s'", id)).Execute()`, the cascade delete DOES happen and the referenced rows in table 2 are removed.

Im really not sure what is going on or why ..

**Comment by ganigeorgiev** [comment] 2023-05-26 13:06
I'm not able to reproduce it locally testing with SQLite. Both should generate the same query.

If you are using SQLite make sure to check https://www.sqlite.org/foreignkeys.html#fk_enable.

I'll close the issue for now as I'm not able to reproduce it and I don't think this is related to the db abstraction, but if you think otherwise please provide reproducible steps and more details about your setup and I'll try to investigate it further.

**Closed as completed by ganigeorgiev** 2023-05-26 13:06 UTC

**Comment by geerew** [comment] 2023-05-26 20:19
My apologies on this one.

I did more digging and for some reason the foreign key on the sqlite DB is flipping to off. I do something similar to pocketbase, whereby when I create the DB connection is do a `PRAGMA foreign_keys = TRUE`. 

I updated my DB store so the CRUD operations output the state of the foreign keys before executing the DB commands. It remains ON for several operations, including some DELETE commands.

But at some stage, for no discernable reason, it randomly flips to OFF ... 

For example , I do a delete and then another delete. It is ON for the first and then OFF for the second

```
[0.00ms] PRAGMA foreign_keys;
[DELETE] ..  FOREIGN KEY = 1
[0.00ms] DELETE FROM `Scans` WHERE `id`='7tjehgs4b9plrly'

(several seconds later with no DB commands inbetween)

[0.00ms] PRAGMA foreign_keys;
[DELETE] ..  FOREIGN KEY = 1
...
```

Anyways, Im sorry for opening this prematurely. I was ripping my hair out with why it worked sometimes and other times it didn't. Now I have another mystery to solve :)

thanks!

**Comment by geerew** [comment] 2023-05-26 21:53
Sorry, me again.

So this is definitely not a problem with dbx, but might impact pocketbase, which I know you work on.

Essentially, when the last idle connection closes, the PRAGMA flags are flipped back to default when a new connection is made. This obviously isnt a problem when there are lots of connections, and idle always has at least 1 connection.

It's pretty easy to test. In PB, set the nonconcurrent and concurrent DB connection timeout to something really small, like 5 seconds 

```
nonconcurrentDB.DB().SetConnMaxIdleTime(5 * time.Second)
``` 

Then wait for 10 to 20 seconds and run a few db commands to see the status of the PRAGMA flags .. 

For example, in my application, I did (where db is a *dbx.DB)

```
var out int
db.NewQuery("PRAGMA busy_timeout;").Row(&out)
fmt.Println("busy_timeout", out)

db.NewQuery("PRAGMA journal_size_limit;").Row(&out)
fmt.Println("journal_size_limit", out)
```

Again, it's up to you if you think this is an issue or not with PB. Took me a long time to figure out .. 

Sorry again, and thanks.

**Comment by ganigeorgiev** [comment] 2023-05-27 03:48
Hm, I'll investigate it later this week. It is possibly related to https://github.com/pocketbase/pocketbase/discussions/2570 which I wasn't able also to reproduce.

**Comment by ganigeorgiev** [comment] 2023-05-27 04:23
Yes, that's indeed the cause of the issue. I don't know why I thought that the PRAGMAs will be automatically executed again on opening new connections. They need to be registered in some sort of hook (the cgo driver has [`ConnectHook`](https://github.com/mattn/go-sqlite3/blob/d366d8de4e44f5c6c37b6b7169a276ee94d0d55b/_example/hook/hook.go#L15)) or defined as part of the db dsn string. I'll fix the issue in PocketBase sometime later today.
